/*
  # exam_feedback_reports (Phase 3 Batch A)

  The post-marking exam report: examiner-style feedback generated by the
  scoring service (server/feedbackRoute.ts in the main repo) in a SEPARATE
  model call after an envelope is already persisted. It never changes a mark
  (main repo ADR 0009): the marks stay in scoring_envelopes, this table holds
  only the feedback.

  - envelope_id is the scored envelope's attempt_id, unique: one report per
    envelope. A second POST /feedback for the same session returns the stored
    row without a model call.
  - feedback_version records EXAM_FEEDBACK_VERSION (src/domain/examFeedback/
    version.ts) of the generator that wrote it.
  - Service key only: RLS is on with NO policies, and anon/authenticated hold
    no privilege at all. The browser reads a report only through
    GET /feedback on the scoring service, which filters by the JWT-verified
    user_id (same owner-enforcement model as scoring_envelopes' server path).
*/

create table if not exists public.exam_feedback_reports (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  envelope_id text not null unique references public.scoring_envelopes(attempt_id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  feedback_version text not null,
  report jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists exam_feedback_reports_session_user_idx
  on public.exam_feedback_reports (session_id, user_id);

alter table public.exam_feedback_reports enable row level security;

revoke all on public.exam_feedback_reports from anon, authenticated;
grant select, insert on public.exam_feedback_reports to service_role;
